13:46:49.86 [WARN] File watcher exiting with: The watcher was shut down.
13:46:51.49 [INFO] Completed: Building local_dists.pex
13:46:51.52 [31m[ERROR][0m 1 Exception encountered:

Engine traceback:
  in `run` goal

InvalidLockfileError: You are consuming `flask`, `flask-migrate`, and 6 other requirements from the `python-default` lockfile at 3rdparty/python/default.lock with incompatible inputs.



- The inputs use interpreter constraints (`CPython==3.12.*`) that are not a subset of those used to generate the lockfile (`CPython==3.11.*`).

- The input interpreter constraints are specified by your code, using the `[python].interpreter_constraints` option and the `interpreter_constraints` target field.

- To create a lockfile with new interpreter constraints, update the option `[python].resolves_to_interpreter_constraints`, and then generate the lockfile (see below).

See https://www.pantsbuild.org/2.20/docs/python/overview/interpreter-compatibility for details.

To regenerate your lockfile, run `pants generate-lockfiles --resolve=python-default`.

See https://www.pantsbuild.org/2.20/docs/python/overview/third-party-dependencies for details.

